import { db, ADMIN_PIN, EVENT_ID, pathFor, yen, localDate, downloadCsv, uuid } from "./common.js";
import { ref, onValue, set, update, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js";
const $=id=>document.getElementById(id), ADMIN_SESSION=`yatai-${EVENT_ID}-admin-open`;let currentSession=null,transactions={},presence={},adminOpen=sessionStorage.getItem(ADMIN_SESSION)==="1";
$("businessDate").value=localDate(new Date());
function sessionTransactions(){return Object.values(transactions).filter(x=>x.sessionId===currentSession?.id)}function canceledIds(list){return new Set(list.filter(x=>x.type==="cancel").map(x=>x.originalTransactionId))}function activeSales(){const list=sessionTransactions(),c=canceledIds(list);return list.filter(x=>x.type==="sale"&&!c.has(x.id))}
function render(){const list=sessionTransactions(),sales=activeSales(),cancels=list.filter(x=>x.type==="cancel"),sum=(arr,key)=>arr.reduce((a,x)=>a+Number(x[key]||0),0),r1=sales.filter(x=>x.registerId==="R1"),r2=sales.filter(x=>x.registerId==="R2");$("sessionBadge").textContent=currentSession?`${currentSession.businessDay}日目 ${currentSession.status==="open"?"営業中":"終了"}`:"営業前";$("startControls").classList.toggle("hidden",currentSession?.status==="open");$("openControls").classList.toggle("hidden",currentSession?.status!=="open");$("totalSales").textContent=yen(sum(sales,"total"));$("saleCount").textContent=`${sales.length}件`;$("cancelCount").textContent=`${cancels.length}件`;$("cancelAmount").textContent=yen(sum(cancels,"total"));$("yakisobaCount").textContent=`${sum(sales,"yakisobaQty")}個`;$("frankCount").textContent=`${sum(sales,"frankfurterQty")}本`;$("r1Sales").textContent=yen(sum(r1,"total"));$("r2Sales").textContent=yen(sum(r2,"total"));$("c1Count").textContent=`${sales.filter(x=>x.cashierId==="C1").length}件`;$("c2Count").textContent=`${sales.filter(x=>x.cashierId==="C2").length}件`;const online=Object.values(presence).filter(x=>x.online);$("r1Status").textContent=`レジ1 ${online.some(x=>x.registerId==="R1")?"接続中":"未接続"}`;$("r2Status").textContent=`レジ2 ${online.some(x=>x.registerId==="R2")?"接続中":"未接続"}`;$("transactionsBody").innerHTML=[...list].sort((a,b)=>(b.clientTime||"").localeCompare(a.clientTime||"")).map(x=>`<tr><td>${new Date(x.clientTime).toLocaleTimeString("ja-JP")}</td><td>${x.receiptNo||"-"}</td><td>${x.registerId}</td><td>${x.cashierId==="C1"?"担当1":"担当2"}</td><td>${x.type==="sale"?"会計":"取消"}</td><td>${x.yakisobaQty}</td><td>${x.frankfurterQty}</td><td>${yen(x.total)}</td><td>${x.reason||""}</td></tr>`).join("")}
function audit(action,detail={}){const id=uuid();set(ref(db,pathFor(`audit/${id}`)),{id,action,detail,actor:"admin",serverTime:serverTimestamp()}).catch(console.error)}
function showAdmin(){adminOpen=true;sessionStorage.setItem(ADMIN_SESSION,"1");$("loginView").classList.add("hidden");$("adminView").classList.remove("hidden");startListeners();audit("admin_open")}
$("loginForm").onsubmit=e=>{e.preventDefault();if($("pin").value!==ADMIN_PIN){$("loginError").textContent="管理PINが違います。";audit("admin_pin_failure");return}showAdmin()};$("logout").onclick=()=>{adminOpen=false;sessionStorage.removeItem(ADMIN_SESSION);$("adminView").classList.add("hidden");$("loginView").classList.remove("hidden")};
$("startSession").onclick=async()=>{const day=Number($("businessDay").value),date=$("businessDate").value;if(!date)return;const id=`${date}-D${day}`;if(!confirm(`${day}日目（${date}）の営業を開始しますか？`))return;await set(ref(db,pathFor(`sessions/${id}`)),{businessDay:day,businessDate:date,status:"open",startedAt:serverTimestamp(),startedBy:"admin"});await set(ref(db,pathFor("settings/currentSession")),id);audit("session_start",{id})};
$("exportCsv").onclick=()=>{const rows=[["営業日","会計番号","サーバー時刻","端末時刻","レジ","担当者","種別","元会計番号","焼きそば","フランク","合計","預かり","お釣り","取消理由","補足"],...sessionTransactions().map(x=>[x.businessDate,x.receiptNo,x.serverTime?new Date(x.serverTime).toLocaleString("ja-JP"):"未同期",new Date(x.clientTime).toLocaleString("ja-JP"),x.registerId,x.cashierId==="C1"?"会計担当1":"会計担当2",x.type==="sale"?"会計":"取消",x.originalReceiptNo||"",x.yakisobaQty,x.frankfurterQty,x.total,x.received,x.change,x.reason||"",x.note||""])];downloadCsv(`屋台売上_全レジ_${currentSession.businessDate}_D${currentSession.businessDay}.csv`,rows);audit("csv_export",{sessionId:currentSession.id,count:rows.length-1})};
$("openClose").onclick=()=>$("closeDialog").showModal();$("cancelClose").onclick=()=>$("closeDialog").close();$("confirmClose").onclick=async()=>{const sales=activeSales(),r1=sales.filter(x=>x.registerId==="R1").reduce((a,x)=>a+x.total,0),r2=sales.filter(x=>x.registerId==="R2").reduce((a,x)=>a+x.total,0),n=id=>Number($(id).value||0),summary={r1:{openingFloat:n("r1Float"),sales:r1,expected:n("r1Float")+r1,actual:n("r1Actual"),difference:n("r1Actual")-(n("r1Float")+r1)},r2:{openingFloat:n("r2Float"),sales:r2,expected:n("r2Float")+r2,actual:n("r2Actual"),difference:n("r2Actual")-(n("r2Float")+r2)},inventory:{yakisobaPrepared:n("yPrepared"),yakisobaRemain:n("yRemain"),yakisobaExpectedSold:n("yPrepared")-n("yRemain"),yakisobaRecorded:sales.reduce((a,x)=>a+x.yakisobaQty,0),frankPrepared:n("fPrepared"),frankRemain:n("fRemain"),frankExpectedSold:n("fPrepared")-n("fRemain"),frankRecorded:sales.reduce((a,x)=>a+x.frankfurterQty,0)},closedAt:serverTimestamp(),closedBy:"admin"};if(!confirm(`営業を締めます。レジ1差額 ${yen(summary.r1.difference)}／レジ2差額 ${yen(summary.r2.difference)}。よろしいですか？`))return;await update(ref(db,pathFor(`sessions/${currentSession.id}`)),{status:"closed",closeSummary:summary});audit("session_close",{sessionId:currentSession.id});$("closeDialog").close()};
let listenersStarted=false;function startListeners(){if(listenersStarted)return;listenersStarted=true;onValue(ref(db,pathFor("settings/currentSession")),snap=>{const id=snap.val();if(!id){currentSession=null;render();return}onValue(ref(db,pathFor(`sessions/${id}`)),s=>{currentSession=s.val()?{id,...s.val()}:null;render()})});onValue(ref(db,pathFor("transactions")),s=>{transactions=s.val()||{};render()});onValue(ref(db,pathFor("presence")),s=>{presence=s.val()||{};render()})}if(adminOpen)showAdmin();else{$("loginView").classList.remove("hidden");$("adminView").classList.add("hidden")}render();
