import { db, EVENT_ID, pathFor, PRICES, yen, uuid } from "./common.js";
import { ref, onValue, set, serverTimestamp, onDisconnect } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js";
const $=id=>document.getElementById(id), OUTBOX=`yatai-${EVENT_ID}-outbox`, SETTINGS=`yatai-${EVENT_ID}-register-settings`, DEVICE_KEY=`yatai-${EVENT_ID}-device-id`;
const deviceId=localStorage.getItem(DEVICE_KEY)||uuid();localStorage.setItem(DEVICE_KEY,deviceId);
let current={yakisoba:0,frankfurter:0,received:0,moneyStack:[]},activeSession=null,transactions={},connected=false,cancelCandidate=null;
const settings=JSON.parse(localStorage.getItem(SETTINGS)||'{"registerId":"R1","cashierId":"C1"}');$("registerId").value=settings.registerId;$("cashierId").value=settings.cashierId;
function getOutbox(){try{return JSON.parse(localStorage.getItem(OUTBOX)||"[]")}catch{return[]}}function saveOutbox(v){localStorage.setItem(OUTBOX,JSON.stringify(v));render()}
function saveSettings(){localStorage.setItem(SETTINGS,JSON.stringify({registerId:$("registerId").value,cashierId:$("cashierId").value}));render()}
function total(){return current.yakisoba*PRICES.yakisoba+current.frankfurter*PRICES.frankfurter}
function mergedTransactions(){const merged={...transactions};getOutbox().forEach(x=>merged[x.id]??=x);return Object.values(merged).filter(x=>x.sessionId===activeSession?.id)}
function canceledIds(list){return new Set(list.filter(x=>x.type==="cancel").map(x=>x.originalTransactionId))}
function validSales(){const list=mergedTransactions(),canceled=canceledIds(list);return list.filter(x=>x.type==="sale"&&!canceled.has(x.id))}
function render(){const t=total(),short=Math.max(t-current.received,0),change=Math.max(current.received-t,0),outbox=getOutbox();$("yakisobaQty").textContent=current.yakisoba;$("frankfurterQty").textContent=current.frankfurter;$("received").textContent=yen(current.received);$("total").textContent=yen(t);$("change").textContent=short?`不足 ${yen(short)}`:yen(change);$("change").classList.toggle("short",short>0);$("checkout").disabled=!activeSession||activeSession.status!=="open"||!t||short>0;$("registerBadge").textContent=$("registerId").selectedOptions[0].text;$("cashierBadge").textContent=$("cashierId").selectedOptions[0].text;$("sessionBadge").textContent=activeSession?`${activeSession.businessDay}日目 ${activeSession.status==="open"?"営業中":"終了"}`:"営業前";$("networkBadge").textContent=connected?"オンライン":"オフライン";$("networkBadge").className=`badge ${connected?"online":"offline"}`;$("outboxBadge").textContent=`未送信 ${outbox.length}件`;const sales=validSales().filter(x=>x.registerId===$("registerId").value),amount=sales.reduce((a,x)=>a+x.total,0),items=sales.reduce((a,x)=>a+x.yakisobaQty+x.frankfurterQty,0);$("registerItems").textContent=`${items}点`;$("registerSales").textContent=yen(amount);$("cancelLast").disabled=!sales.length}
function nextReceipt(){const time=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date()).replaceAll(":",""),random=uuid().replaceAll("-","").slice(0,3).toUpperCase();return `D${activeSession.businessDay}-${$("registerId").value}-${time}-${random}`}
async function queue(record){const list=getOutbox();if(!list.some(x=>x.id===record.id))list.push(record);saveOutbox(list);flushOutbox()}
async function flushOutbox(){if(!connected)return;for(const item of getOutbox()){try{await set(ref(db,pathFor(`transactions/${item.id}`)),{...item,serverTime:serverTimestamp()});saveOutbox(getOutbox().filter(x=>x.id!==item.id))}catch(err){console.error(err);break}}}
function audit(action,detail={}){const id=uuid();set(ref(db,pathFor(`audit/${id}`)),{id,action,detail,deviceId,registerId:$("registerId").value,cashierId:$("cashierId").value,serverTime:serverTimestamp()}).catch(console.error)}
function updatePresence(){if(!connected)return;const p=ref(db,pathFor(`presence/${deviceId}`));set(p,{online:true,registerId:$("registerId").value,cashierId:$("cashierId").value,lastSeen:serverTimestamp()});onDisconnect(p).set({online:false,registerId:$("registerId").value,cashierId:$("cashierId").value,lastSeen:serverTimestamp()})}
[$("registerId"),$("cashierId")].forEach(el=>el.onchange=()=>{saveSettings();updatePresence();audit("operator_change",{registerId:$("registerId").value,cashierId:$("cashierId").value})});
document.querySelectorAll("[data-product]").forEach(b=>b.onclick=()=>{const k=b.dataset.product;current[k]=Math.max(0,current[k]+Number(b.dataset.delta));render()});document.querySelectorAll("[data-money]").forEach(b=>b.onclick=()=>{const n=Number(b.dataset.money);current.received+=n;current.moneyStack.push(n);render()});
$("undoMoney").onclick=()=>{current.received=Math.max(0,current.received-(current.moneyStack.pop()||0));render()};$("exactMoney").onclick=()=>{current.received=total();current.moneyStack=[];render()};
$("checkout").onclick=()=>{const amount=total();if(!activeSession||!amount||current.received<amount)return;const record={id:uuid(),type:"sale",receiptNo:nextReceipt(),sessionId:activeSession.id,businessDay:activeSession.businessDay,businessDate:activeSession.businessDate,registerId:$("registerId").value,cashierId:$("cashierId").value,deviceId,clientTime:new Date().toISOString(),yakisobaQty:current.yakisoba,frankfurterQty:current.frankfurter,total:amount,received:current.received,change:current.received-amount};queue(record);current={yakisoba:0,frankfurter:0,received:0,moneyStack:[]};$("notice").textContent=`${record.receiptNo} 会計完了`;setTimeout(()=>$("notice").textContent="",2500);render()};
$("cancelLast").onclick=()=>{cancelCandidate=[...validSales()].filter(x=>x.registerId===$("registerId").value).sort((a,b)=>(b.clientTime||"").localeCompare(a.clientTime||""))[0];if(!cancelCandidate)return;$("cancelTarget").textContent=`${cancelCandidate.receiptNo}／${yen(cancelCandidate.total)}`;$("cancelDialog").showModal()};
$("confirmCancel").onclick=e=>{e.preventDefault();if(!cancelCandidate)return;const record={id:uuid(),type:"cancel",receiptNo:nextReceipt(),originalTransactionId:cancelCandidate.id,originalReceiptNo:cancelCandidate.receiptNo,reason:$("cancelReason").value,note:$("cancelNote").value.trim(),sessionId:activeSession.id,businessDay:activeSession.businessDay,businessDate:activeSession.businessDate,registerId:$("registerId").value,cashierId:$("cashierId").value,deviceId,clientTime:new Date().toISOString(),yakisobaQty:cancelCandidate.yakisobaQty,frankfurterQty:cancelCandidate.frankfurterQty,total:cancelCandidate.total,received:0,change:0};queue(record);audit("cancel_sale",{originalReceiptNo:cancelCandidate.receiptNo,reason:record.reason});$("cancelDialog").close();cancelCandidate=null};
onValue(ref(db,".info/connected"),snap=>{connected=!!snap.val();render();if(connected){updatePresence();flushOutbox()}});onValue(ref(db,pathFor("settings/currentSession")),snap=>{const id=snap.val();if(!id){activeSession=null;render();return}onValue(ref(db,pathFor(`sessions/${id}`)),s=>{activeSession=s.val()?{id,...s.val()}:null;render()})});onValue(ref(db,pathFor("transactions")),snap=>{transactions=snap.val()||{};render()});audit("register_open");render();
